// Copyright (c) 2025-2026 Littleton Robotics
// http://github.com/Mechanical-Advantage
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file at
// the root directory of this project.

package org.littletonrobotics.idun;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashSet;
import java.util.Set;
import java.util.function.Consumer;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

class IdunNativeIOGenerator {
  static void generate(
      Element sourceClass,
      Element inputsClass,
      Element outputsClass,
      ProcessingEnvironment processingEnv) {
    String ioName = sourceClass.getSimpleName().toString();
    String subsytemName = ioName.substring(0, ioName.length() - 2);

    // Create header file
    try {
      FileObject fileObject =
          processingEnv
              .getFiler()
              .createResource(
                  StandardLocation.NATIVE_HEADER_OUTPUT, "", ioName + ".h", sourceClass);

      try (PrintWriter writer = new PrintWriter(fileObject.openWriter())) {
        StringBuilder structsBuilder = new StringBuilder();
        Set<String> includePaths = new HashSet<>();
        Consumer<Boolean> addIOStruct =
            (Boolean isInputs) -> {
              structsBuilder.append(
                  String.format("""
  struct %s {
""", ioName + (isInputs ? "Inputs" : "Outputs")));
              for (var element : (isInputs ? inputsClass : outputsClass).getEnclosedElements()) {
                if (element.getKind() != ElementKind.FIELD) continue;

                if (!IdunAnnotationProcessor.isEnum(element, processingEnv)) {
                  switch (element.asType().toString()) {
                    case "double" -> {
                      structsBuilder.append(
                          String.format("    double %s;\n", element.getSimpleName().toString()));
                    }
                    case "edu.wpi.first.math.geometry.Rotation2d" -> {
                      structsBuilder.append(
                          String.format(
                              "    frc::Rotation2d %s;\n", element.getSimpleName().toString()));
                    }
                    case "boolean" -> {
                      structsBuilder.append(
                          String.format("    bool %s;\n", element.getSimpleName().toString()));
                    }
                    case "byte[]" -> {
                      structsBuilder.append(
                          String.format(
                              "    std::string %s;\n", element.getSimpleName().toString()));
                    }
                  }
                } else {
                  var fieldType = processingEnv.getTypeUtils().asElement(element.asType());
                  IdunNativeEnumGenerator.generateEnum(fieldType, processingEnv);
                  structsBuilder.append(
                      String.format(
                          "    %s %s;\n",
                          fieldType.getSimpleName(), element.getSimpleName().toString()));
                  includePaths.add("\"" + fieldType.getSimpleName() + ".h\"");
                }
              }
              structsBuilder.append(String.format("""
  };

"""));
            };
        addIOStruct.accept(true);
        addIOStruct.accept(false);

        writer.format(
            """
// This file is autogenerated based on the Java class \"%s\"

#pragma once

#include "idun/SubsystemIO.h"
#include <frc/geometry/Rotation2d.h>
""",
            sourceClass.asType().toString());
        for (var path : includePaths) {
          writer.format("#include %s\n", path);
        }
        writer.format(
            """

class %s : public idun::SubsystemIO {
public:
  %s();
  %s(std::string_view name);

%s  // ******** THE FOLLOWING METHODS MUST BE INCLUDED IN THE IO IMPLEMENTATION ********
  virtual void updateInputs(%sInputs &inputs) = 0;
  virtual void applyOutputs(const %sOutputs &outputs) = 0;
  virtual void stop() = 0;
  // *********************************************************************************

protected:
  void updateInputsProto(idun::proto::IOData &inputs) override;
  void applyOutputsProto(const idun::proto::IOData &outputs) override;
};
""",
            ioName, ioName, ioName, structsBuilder.toString(), ioName, ioName);
      }
    } catch (IOException e) {
      e.printStackTrace();
    }

    // Create implementation file
    try {
      FileObject fileObject =
          processingEnv
              .getFiler()
              .createResource(
                  StandardLocation.NATIVE_HEADER_OUTPUT, "", ioName + ".cpp", sourceClass);

      try (PrintWriter writer = new PrintWriter(fileObject.openWriter())) {
        writer.format(
            """
// This file is autogenerated based on the Java class \"%s\"

#include "%s.h"

%s::%s() : SubsystemIO::SubsystemIO("%s") {};

%s::%s(std::string_view name) : SubsystemIO::SubsystemIO(name) {};

""",
            sourceClass.asType().toString(), ioName, ioName, ioName, subsytemName, ioName, ioName);

        // Create update inputs method
        writer.format(
            """
void %s::updateInputsProto(idun::proto::IOData &inputs) {
  %sInputs inputsStruct;
  updateInputs(inputsStruct);
  inputs.Clear();
""",
            ioName, ioName);
        for (var element : inputsClass.getEnclosedElements()) {
          if (element.getKind() != ElementKind.FIELD) continue;
          if (!IdunAnnotationProcessor.isEnum(element, processingEnv)) {
            switch (element.asType().toString()) {
              case "double" -> {
                writer.format(
                    "  inputs.add_double_(inputsStruct.%s);\n", element.getSimpleName().toString());
              }
              case "edu.wpi.first.math.geometry.Rotation2d" -> {
                writer.format(
                    "  inputs.add_double_(inputsStruct.%s.Radians().value());\n",
                    element.getSimpleName().toString());
              }
              case "boolean" -> {
                writer.format(
                    "  inputs.add_boolean(inputsStruct.%s);\n", element.getSimpleName().toString());
              }
              case "byte[]" -> {
                writer.format(
                    "  inputs.add_raw(inputsStruct.%s);\n", element.getSimpleName().toString());
              }
            }
          } else {
            writer.format(
                "  inputs.add_enum_(static_cast<int32_t>(inputsStruct.%s));\n",
                element.getSimpleName().toString());
          }
        }
        writer.format("};\n\n", ioName);

        // Create apply outputs methods
        writer.format(
            """
void %s::applyOutputsProto(const idun::proto::IOData &outputs) {
  %sOutputs outputsStruct;
""",
            ioName, ioName);
        int doubleIndex = 0;
        int booleanIndex = 0;
        int rawIndex = 0;
        for (var element : outputsClass.getEnclosedElements()) {
          if (element.getKind() != ElementKind.FIELD) continue;
          if (!IdunAnnotationProcessor.isEnum(element, processingEnv)) {
            switch (element.asType().toString()) {
              case "double" -> {
                writer.format(
                    "  outputsStruct.%s = outputs.double_(%d);\n",
                    element.getSimpleName().toString(), doubleIndex++);
              }
              case "edu.wpi.first.math.geometry.Rotation2d" -> {
                writer.format(
                    "  outputsStruct.%s = frc::Rotation2d(units::angle::radian_t{outputs.double_(%d)});\n",
                    element.getSimpleName().toString(), doubleIndex++);
              }
              case "boolean" -> {
                writer.format(
                    "  outputsStruct.%s = outputs.boolean(%d);\n",
                    element.getSimpleName().toString(), booleanIndex++);
              }
              case "byte[]" -> {
                writer.format(
                    "  outputsStruct.%s = outputs.raw(%d);\n",
                    element.getSimpleName().toString(), rawIndex++);
              }
            }
          } else {
            var fieldType = processingEnv.getTypeUtils().asElement(element.asType());
            writer.format(
                "  outputsStruct.%s = static_cast<%s>(outputs.enum_(%d));\n",
                element.getSimpleName().toString(), fieldType.getSimpleName(), rawIndex++);
          }
        }

        // Finish file
        writer.format("""
  applyOutputs(outputsStruct);
};
""", ioName, ioName);
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  private IdunNativeIOGenerator() {}
}
