// Copyright (c) 2025-2026 Littleton Robotics
// http://github.com/Mechanical-Advantage
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file at
// the root directory of this project.

package org.littletonrobotics.idun;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;
import java.io.IOException;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.tools.Diagnostic;

class IdunJavaIOGenerator {
  static void generate(
      Element sourceClass,
      Element inputsClass,
      Element outputsClass,
      ProcessingEnvironment processingEnv) {
    String ioName = sourceClass.getSimpleName().toString();
    String subsytemName = ioName.substring(0, ioName.length() - 2);
    TypeSpec.Builder typeBuilder =
        TypeSpec.classBuilder(ioName + "Idun")
            .addModifiers(Modifier.PUBLIC)
            .addSuperinterface(sourceClass.asType())
            .addJavadoc(
                String.format(
                    "This file is autogenerated based on the class \"%s\"",
                    sourceClass.asType().toString()));

    // Create constructors
    typeBuilder.addField(
        FieldSpec.builder(String.class, "name", Modifier.PRIVATE, Modifier.FINAL).build());
    typeBuilder.addMethod(
        MethodSpec.constructorBuilder()
            .addModifiers(Modifier.PUBLIC)
            .addCode(String.format("this(\"%s\");", subsytemName))
            .build());
    typeBuilder.addMethod(
        MethodSpec.constructorBuilder()
            .addModifiers(Modifier.PUBLIC)
            .addParameter(String.class, "name")
            .addCode("this.name = name;")
            .build());

    // Create inputs implementation
    MethodSpec.Builder updateInputs =
        MethodSpec.methodBuilder("updateInputs")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(TypeName.get(inputsClass.asType()), "inputs")
            .addCode(
                "org.littletonrobotics.idun.IdunComms.IOData inputsProto = org.littletonrobotics.idun.IdunServer.getSubsystemInputs(name);\n")
            .addCode("if (inputsProto == null) return;\n");
    int doubleIndex = 0;
    int booleanIndex = 0;
    int rawIndex = 0;
    int enumIndex = 0;
    for (var element : inputsClass.getEnclosedElements()) {
      if (element.getKind() != ElementKind.FIELD) continue;

      if (!IdunAnnotationProcessor.isEnum(element, processingEnv)) {
        switch (element.asType().toString()) {
          case "double" -> {
            updateInputs.addCode(
                String.format(
                    "inputs.%s = inputsProto.getDouble(%d);\n",
                    element.getSimpleName(), doubleIndex++));
          }
          case "edu.wpi.first.math.geometry.Rotation2d" -> {
            updateInputs.addCode(
                String.format(
                    "inputs.%s = edu.wpi.first.math.geometry.Rotation2d.fromRadians(inputsProto.getDouble(%d));\n",
                    element.getSimpleName(), doubleIndex++));
          }
          case "boolean" -> {
            updateInputs.addCode(
                String.format(
                    "inputs.%s = inputsProto.getBoolean(%d);\n",
                    element.getSimpleName(), booleanIndex++));
          }
          case "byte[]" -> {
            updateInputs.addCode(
                String.format(
                    "inputs.%s = inputsProto.getRaw(%d).toByteArray();\n",
                    element.getSimpleName(), rawIndex++));
          }
        }
      } else {
        updateInputs.addCode(
            String.format(
                "inputs.%s = %s.values()[inputsProto.getEnum(%d)];\n",
                element.getSimpleName(), element.asType().toString(), enumIndex++));
      }
    }
    typeBuilder.addMethod(updateInputs.build());

    // Create outputs implementation
    typeBuilder.addField(
        FieldSpec.builder(
                ClassName.get("org.littletonrobotics.idun.IdunComms", "IOData", "Builder"),
                "outputsBuilder",
                Modifier.PRIVATE)
            .initializer("IOData.newBuilder()")
            .build());
    MethodSpec.Builder applyOutputs =
        MethodSpec.methodBuilder("applyOutputs")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(TypeName.get(outputsClass.asType()), "outputs")
            .addCode("outputsBuilder.clear();\n");
    for (var element : outputsClass.getEnclosedElements()) {
      if (element.getKind() != ElementKind.FIELD) continue;

      if (!IdunAnnotationProcessor.isEnum(element, processingEnv)) {
        switch (element.asType().toString()) {
          case "double" -> {
            applyOutputs.addCode(
                String.format("outputsBuilder.addDouble(outputs.%s);\n", element.getSimpleName()));
          }
          case "edu.wpi.first.math.geometry.Rotation2d" -> {
            applyOutputs.addCode(
                String.format(
                    "outputsBuilder.addDouble(outputs.%s.getRadians());\n",
                    element.getSimpleName()));
          }
          case "boolean" -> {
            applyOutputs.addCode(
                String.format("outputsBuilder.addBoolean(outputs.%s);\n", element.getSimpleName()));
          }
          case "byte[]" -> {
            applyOutputs.addCode(
                String.format(
                    "outputsBuilder.addRaw(com.google.protobuf.ByteString.copyFrom(outputs.%s));\n",
                    element.getSimpleName()));
          }
        }
      } else {
        applyOutputs.addCode(
            String.format(
                "outputsBuilder.addEnum(outputs.%s.ordinal());\n", element.getSimpleName()));
      }
    }
    applyOutputs.addCode(
        "org.littletonrobotics.idun.IdunServer.setSubsystemOutputs(name, outputsBuilder.build());\n");
    typeBuilder.addMethod(applyOutputs.build());

    // Write to file
    JavaFile file =
        JavaFile.builder(IdunAnnotationProcessor.getPackageName(sourceClass), typeBuilder.build())
            .build();
    try {
      file.writeTo(processingEnv.getFiler());
    } catch (IOException e) {
      processingEnv
          .getMessager()
          .printMessage(Diagnostic.Kind.ERROR, "Failed to write Idun implementation", sourceClass);
      e.printStackTrace();
    }
  }

  private IdunJavaIOGenerator() {}
}
