// Copyright (c) 2025-2026 Littleton Robotics
// http://github.com/Mechanical-Advantage
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file at
// the root directory of this project.

package org.littletonrobotics.idun;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import javax.annotation.processing.FilerException;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

class IdunNativeEnumGenerator {
  static void generateEnum(Element enumClass, ProcessingEnvironment processingEnv) {
    try {
      FileObject fileObject =
          processingEnv
              .getFiler()
              .createResource(
                  StandardLocation.NATIVE_HEADER_OUTPUT,
                  "",
                  enumClass.getSimpleName().toString() + ".h",
                  enumClass);

      try (PrintWriter writer = new PrintWriter(fileObject.openWriter())) {
        AtomicInteger index = new AtomicInteger(0);
        writer.format(
            """
// This file is autogenerated based on the Java class \"%s\"

#pragma once

enum class %s {
  %s
};
""",
            enumClass.asType().toString(),
            enumClass.getSimpleName().toString(),
            enumClass.getEnclosedElements().stream()
                .filter((element) -> element.getKind() == ElementKind.ENUM_CONSTANT)
                .map(
                    (element) -> {
                      return element.getSimpleName().toString()
                          + " = "
                          + Integer.toString(index.getAndIncrement());
                    })
                .collect(Collectors.joining(",\n  ")),
            enumClass.getSimpleName().toString());
      }
    } catch (FilerException e) {
      // Already generated, OK to proceed
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  private IdunNativeEnumGenerator() {}
}
