// Copyright (c) 2025-2026 Littleton Robotics
// http://github.com/Mechanical-Advantage
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file at
// the root directory of this project.

package org.littletonrobotics.idun;

import com.sun.source.tree.ExpressionTree;
import com.sun.source.tree.MemberSelectTree;
import com.sun.source.tree.Tree;
import com.sun.source.tree.VariableTree;
import com.sun.source.util.Trees;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashSet;
import java.util.Set;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.VariableElement;
import javax.tools.FileObject;
import javax.tools.StandardLocation;

class IdunNativeConstantsGenerator {
  static void generate(Element sourceClass, ProcessingEnvironment processingEnv) {
    // Get trees
    Trees trees = Trees.instance(processingEnv);

    // Create header file
    try {
      FileObject fileObject =
          processingEnv
              .getFiler()
              .createResource(
                  StandardLocation.NATIVE_HEADER_OUTPUT,
                  "",
                  sourceClass.getSimpleName().toString() + ".h",
                  sourceClass);

      try (PrintWriter writer = new PrintWriter(fileObject.openWriter())) {
        writer.format(
            """
// This file is autogenerated based on the Java class \"%s\"

#pragma once

""",
            sourceClass.asType().toString());

        // Add constants
        StringBuilder valueBuilder = new StringBuilder();
        Set<String> includePaths = new HashSet<>();
        sourceClass.getEnclosedElements().stream()
            .filter(
                element ->
                    element.getKind() == ElementKind.FIELD
                        && element.getModifiers().contains(Modifier.FINAL)
                        && element.getModifiers().contains(Modifier.STATIC))
            .forEach(
                element -> {
                  var field = (VariableElement) element;

                  // Try to write as primitive or string
                  if (field.getConstantValue() != null) {
                    switch (element.asType().getKind()) {
                      case BOOLEAN -> {
                        valueBuilder.append(
                            String.format(
                                "constexpr bool %s = %s;\n",
                                field.getSimpleName(), field.getConstantValue().toString()));
                      }
                      case BYTE -> {
                        valueBuilder.append(
                            String.format(
                                "constexpr char %s = %s;\n",
                                field.getSimpleName(), field.getConstantValue().toString()));
                      }
                      case SHORT -> {
                        valueBuilder.append(
                            String.format(
                                "constexpr short %s = %s;\n",
                                field.getSimpleName(), field.getConstantValue().toString()));
                      }
                      case INT -> {
                        valueBuilder.append(
                            String.format(
                                "constexpr int %s = %s;\n",
                                field.getSimpleName(), field.getConstantValue().toString()));
                      }
                      case LONG -> {
                        valueBuilder.append(
                            String.format(
                                "constexpr long long %s = %sL;\n",
                                field.getSimpleName(), field.getConstantValue().toString()));
                      }
                      case FLOAT -> {
                        valueBuilder.append(
                            String.format(
                                "constexpr float %s = %s;\n",
                                field.getSimpleName(), field.getConstantValue().toString()));
                      }
                      case DOUBLE -> {
                        valueBuilder.append(
                            String.format(
                                "constexpr double %s = %s;\n",
                                field.getSimpleName(), field.getConstantValue().toString()));
                      }
                      case DECLARED -> {
                        if (field.asType().toString().equals("java.lang.String")) {
                          valueBuilder.append(
                              String.format(
                                  "constexpr std::string_view %s = \"%s\";\n",
                                  field.getSimpleName(), field.getConstantValue().toString()));
                          includePaths.add("<string_view>");
                        }
                      }
                      default -> {}
                    }
                  }

                  // Try to write as enum
                  var fieldType = processingEnv.getTypeUtils().asElement(field.asType());
                  if (fieldType != null && fieldType.getKind() == ElementKind.ENUM) {
                    var fieldTree = (VariableTree) trees.getTree(field);
                    if (fieldTree == null) return;
                    ExpressionTree fieldInitializer = fieldTree.getInitializer();
                    if (fieldInitializer != null
                        && fieldInitializer.getKind() == Tree.Kind.MEMBER_SELECT) {
                      IdunNativeEnumGenerator.generateEnum(fieldType, processingEnv);
                      String value =
                          ((MemberSelectTree) fieldInitializer).getIdentifier().toString();
                      valueBuilder.append(
                          String.format(
                              "constexpr %s %s = %s::%s;\n",
                              fieldType.getSimpleName(),
                              field.getSimpleName(),
                              fieldType.getSimpleName(),
                              value));
                      includePaths.add("\"" + fieldType.getSimpleName() + ".h\"");
                    }
                  }
                });

        // Write includes
        for (var path : includePaths) {
          writer.format("#include %s\n", path);
        }
        if (includePaths.size() > 0) {
          writer.format("\n");
        }

        // Finish file
        writer.format(
            """
namespace %s {

%s
}; // namespace %s
""",
            sourceClass.getSimpleName().toString(),
            valueBuilder.toString(),
            sourceClass.getSimpleName().toString());
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  private IdunNativeConstantsGenerator() {}
}
